Account page branch
tg-netflix/frontend pull request #5
Opened 2022-09-30 14:29 UTC by Esther2504

Volledige Account pagina met mobile version

Het component staat in App.js voor het testen & er zijn tijdelijke placeholders voor de navbar en footer

2022-10-03 06:19 UTC, 8e9one approved these changes

2022-10-03 11:54 UTC, Sander-G requested changes
Vrijwel niet van echt te onderscheiden (bijna per ongeluk m'n eigen membership gecanceld). 

Paar kleine lettertype kleur dingetjes. Erg cool hoe je de gebruikersdata importeert ipv. hardcode en de billing datum 'vooruitschuift'. very nice. 
sander.

2022-10-03 11:54 UTC, Sander-G commented on TG-Netflix/src/pages/account/AccountPage.styled.jsx
> +}
vs code verwacht hier een curly bracket?  misschien die geopend is op line 235, er staat een closing bracket op line 301, als je deze verplaatst naar line 284 gaat de error weg.

2022-10-03 11:54 UTC, Sander-G commented on TG-Netflix/src/components/account-page/SettingsSection.jsx
> +              <a href="">
misschien kan de 'sign out of all devices' link terug gaan naar de landingspage

2022-10-03 11:54 UTC, Sander-G commented on TG-Netflix/src/components/account-page/MembershipSection.jsx
> +            <p>Password: *******</p>
Password heeft als textkleur grijs ipv zwart

2022-10-03 11:54 UTC, Sander-G commented on TG-Netflix/src/components/account-page/ProfileSection.jsx
> +                    <p>{profile.language}</p>
de 'instellingen' zijn grijs ipv zwart, dit klopt wel bij "John / All maturity ratings" (John = zwart, All maturity ratings is grijs), maar uitgeklapt hebben de items allemaal tekstkleur zwart

2022-10-04 08:16 UTC, lextirajoh approved these changes

2022-10-04 08:41 UTC, Sander-G approved these changes

2022-10-04 10:54 UTC, merged